name: Deploy to VPS 

on:
  push:
    branches:
      - main # Jalankan otomatisasi hanya jika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}       # IP VPS lo (disembunyikan)
          username: ${{ secrets.VPS_USER }}   # Username root (disembunyikan)
          key: ${{ secrets.VPS_SSH_KEY }}     # SSH Private Key lo (disembunyikan)
          port: 22
          script: |
            
            cd /home/mupi/uas-pak-endy-2-matkul
            
            
            git reset --hard origin/main
            
            
            git pull origin main
            
            
            docker compose up -d --build